language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coveralls
